//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to აფხაზეთი.
        /// </summary>
        public static string Abkhazia {
            get {
                return ResourceManager.GetString("Abkhazia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მისამართი.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კონტაქტი.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ახალი.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დაბადების თარიღი.
        /// </summary>
        public static string Dateofbirth {
            get {
                return ResourceManager.GetString("Dateofbirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ნოტიფიკაცია ოკუპირებულ ტერიტორიებზე შესვლის თაობაზე საქართველოში მომუშავე და ოკუპირებული რეგიონების მონახულების მსურველმა პირებმა საჭიროა შეავსონ ქვემდებარე ფორმა. სანოტიფიკაციო ფორმა არ აკისრებს სახელმწიფო მინისტრის აპარატს რაიმე პასუხისმგებლობას და არ წარმოადგენს ოკუპირებული რეგიონების მონახულების ნებართვას. სანოტიფიკაციო ფორმა არის მხოლოდ ინფორმაციული ხასიათის. საერთაშორისო ჟურნალისტების მიერ მედიააკრედიტაციის მიღების მიზნით გთხოვთ დაუკავშირდეთ საქართველოს საგარეო საქმეთა სამინისტროს ან გადახვიდეთ ამ ბმუ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Desc1 {
            get {
                return ResourceManager.GetString("Desc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დანიშნულების ადგილი.
        /// </summary>
        public static string Destinationplace {
            get {
                return ResourceManager.GetString("Destinationplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დროის შუალედი.
        /// </summary>
        public static string Durationofstay {
            get {
                return ResourceManager.GetString("Durationofstay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ელ-ფოსტა.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გადაუდებელ შემთხვევაში საკონტაქტო პირი.
        /// </summary>
        public static string Emergency_Contacts {
            get {
                return ResourceManager.GetString("Emergency Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფაქსი.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დაწყების თარიღი.
        /// </summary>
        public static string FDate {
            get {
                return ResourceManager.GetString("FDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სახელი.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -დან.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გალერეა.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სქესი.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მასპინძლის საკონტაქტო ინფორმაცია.
        /// </summary>
        public static string HostContact {
            get {
                return ResourceManager.GetString("HostContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მასპინძლის სახელი, გვარი.
        /// </summary>
        public static string HostsName {
            get {
                return ResourceManager.GetString("HostsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მნიშვნელოვანი დოკუმენტები.
        /// </summary>
        public static string ImportantDocs {
            get {
                return ResourceManager.GetString("ImportantDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სამოქალაქო ინტეგრაცია.
        /// </summary>
        public static string Integration {
            get {
                return ResourceManager.GetString("Integration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გვარი.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დასრულების თარიღი.
        /// </summary>
        public static string LDate {
            get {
                return ResourceManager.GetString("LDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შესვლა.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მთავარი.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მოქალაქეობა.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სიახლეები.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სანოტიფიკაციო ფორმები.
        /// </summary>
        public static string NotificationForms {
            get {
                return ResourceManager.GetString("NotificationForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მინისტრის აპარატი.
        /// </summary>
        public static string OfficeOfTheMinister {
            get {
                return ResourceManager.GetString("OfficeOfTheMinister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სამხრეთ ოსეთი.
        /// </summary>
        public static string Ossetia {
            get {
                return ResourceManager.GetString("Ossetia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პასპორტის ნომერი.
        /// </summary>
        public static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პაროლი.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პერსონალური ინფორმაცია.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to განსახორციელებელი პროექტი.
        /// </summary>
        public static string ProjectImplemented {
            get {
                return ResourceManager.GetString("ProjectImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შესვლის მიზანი.
        /// </summary>
        public static string PurposeofVisit {
            get {
                return ResourceManager.GetString("PurposeofVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დამიმახსოვრე.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სტატუს ნეიტრალური დოკუმენტები.
        /// </summary>
        public static string StatusNeutralDocs {
            get {
                return ResourceManager.GetString("StatusNeutralDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტელეფონი.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შენახვა.
        /// </summary>
        public static string TextSave {
            get {
                return ResourceManager.GetString("TextSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დროის შუალედი.
        /// </summary>
        public static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -მდე.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ატვირთეთ ფოტო.
        /// </summary>
        public static string UploadPhoto {
            get {
                return ResourceManager.GetString("UploadPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მომხმარებელი.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტრანსპორტის სახე.
        /// </summary>
        public static string Vehicletype {
            get {
                return ResourceManager.GetString("Vehicletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ვიზიტის ორგანიზატორი.
        /// </summary>
        public static string VisitOrganizedby {
            get {
                return ResourceManager.GetString("VisitOrganizedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მომხმარებელი ან პაროლი არასწორია.
        /// </summary>
        public static string WorningWrongPassword {
            get {
                return ResourceManager.GetString("WorningWrongPassword", resourceCulture);
            }
        }
    }
}
