//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to აფხაზეთი.
        /// </summary>
        public static string Abkhazia {
            get {
                return ResourceManager.GetString("Abkhazia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დამატებითი ინფორმაცია..
        /// </summary>
        public static string AddInfo {
            get {
                return ResourceManager.GetString("AddInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მისამართი.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პროექტის მიზანი.
        /// </summary>
        public static string AimOfProject {
            get {
                return ResourceManager.GetString("AimOfProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ინფორმაცია რეგისტრაციის შესახებ (რეგისტრაციის არსებობის შემთხვევაში).
        /// </summary>
        public static string ApplicableUpload {
            get {
                return ResourceManager.GetString("ApplicableUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კონტაქტი.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to საკონტაქტო პირი (სახელი, გვარი, ტელეფონი).
        /// </summary>
        public static string ContactForm1 {
            get {
                return ResourceManager.GetString("ContactForm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2009-2015 შერიგებისა და სამოქალაქო.
        /// </summary>
        public static string cp1 {
            get {
                return ResourceManager.GetString("cp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to თანასწორობის საკითხებში საქართველოს სახელმწიფო.
        /// </summary>
        public static string cp2 {
            get {
                return ResourceManager.GetString("cp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მინისტრის აპარატი. ყველა უფლება დაცულია..
        /// </summary>
        public static string cp3 {
            get {
                return ResourceManager.GetString("cp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ახალი.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დაბადების თარიღი.
        /// </summary>
        public static string Dateofbirth {
            get {
                return ResourceManager.GetString("Dateofbirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ნოტიფიკაცია ოკუპირებულ ტერიტორიებზე შესვლის თაობაზე საქართველოში მომუშავე და ოკუპირებული რეგიონების მონახულების მსურველმა პირებმა საჭიროა შეავსონ ქვემდებარე ფორმა. სანოტიფიკაციო ფორმა არ აკისრებს სახელმწიფო მინისტრის აპარატს რაიმე პასუხისმგებლობას და არ წარმოადგენს ოკუპირებული რეგიონების მონახულების ნებართვას. სანოტიფიკაციო ფორმა არის მხოლოდ ინფორმაციული ხასიათის. საერთაშორისო ჟურნალისტების მიერ მედიააკრედიტაციის მიღების მიზნით გთხოვთ დაუკავშირდეთ საქართველოს საგარეო საქმეთა სამინისტროს ან გადახვიდეთ ამ ბმუ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Desc1 {
            get {
                return ResourceManager.GetString("Desc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ოკუპირებულ ტერიტორიებზე არასამეწარმეო საქმიანობის განხორციელებისათვის .
        /// </summary>
        public static string DescForm3 {
            get {
                return ResourceManager.GetString("DescForm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ორგანიზაციის მისიის აღწერა.
        /// </summary>
        public static string DescOfOrg {
            get {
                return ResourceManager.GetString("DescOfOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დანიშნულების ადგილი.
        /// </summary>
        public static string Destinationplace {
            get {
                return ResourceManager.GetString("Destinationplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დონორები.
        /// </summary>
        public static string Donor_s_ {
            get {
                return ResourceManager.GetString("Donor(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დონორები (დასახელება და საკონტაქტო ინფორმაცია).
        /// </summary>
        public static string DonorsForm2 {
            get {
                return ResourceManager.GetString("DonorsForm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პროექტი ერთობლივად არის წარდგენილი დონორისა და პროექტის წარმდგენელის მიერ (კი/არა). დადებითი პასუხის შემთხვევაში: დონორ(ებ)ის დასახელება.
        /// </summary>
        public static string DonorsForm3 {
            get {
                return ResourceManager.GetString("DonorsForm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დროის შუალედი.
        /// </summary>
        public static string Durationofstay {
            get {
                return ResourceManager.GetString("Durationofstay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ელ-ფოსტა.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EmailPassword {
            get {
                return ResourceManager.GetString("EmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გადაუდებელ შემთხვევაში საკონტაქტო პირი.
        /// </summary>
        public static string Emergency_Contacts {
            get {
                return ResourceManager.GetString("Emergency Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გადაუდებელი ჰუმანიტარული დახმარების გაცემის ვადა (ერთჯერადი, მრავალჯერადი).
        /// </summary>
        public static string EmerHum {
            get {
                return ResourceManager.GetString("EmerHum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პროექტის მოსალოდნელი შედეგები.
        /// </summary>
        public static string ExpectedResults {
            get {
                return ResourceManager.GetString("ExpectedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფაქსი.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დაწყების თარიღი.
        /// </summary>
        public static string FDate {
            get {
                return ResourceManager.GetString("FDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დასაშვები ფაილები: &quot;.jpg&quot;,&quot;.pdf,&quot;.rar&quot;.
        /// </summary>
        public static string fileextensions {
            get {
                return ResourceManager.GetString("fileextensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფინანსური ინფორმაცია (მოსალოდნელი ბიუჯეტი, რესურსები, საბანკო ინფორმაცია).
        /// </summary>
        public static string FinanceInfo {
            get {
                return ResourceManager.GetString("FinanceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სახელი.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შენიშვნა: განაცხადის ფორმა არ წარმოადგენს ოკუპირებულ რეგიონებში შესვლის გარანტიას .
        /// </summary>
        public static string FNote {
            get {
                return ResourceManager.GetString("FNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -დან.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გალერეა.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სქესი.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ზოგადი ინფორმაცია.
        /// </summary>
        public static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მასპინძლის საკონტაქტო ინფორმაცია.
        /// </summary>
        public static string HostContact {
            get {
                return ResourceManager.GetString("HostContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მასპინძლის სახელი, გვარი.
        /// </summary>
        public static string HostsName {
            get {
                return ResourceManager.GetString("HostsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ჰუმანიტარული მდგომარეობის აღწერა (რით არის გამოწვეული, რომელ გეოგრაფიულ არეალს მოიცავს ჰუმანიტარული მდგომარეობის მიერ გამოწვეული შედეგები).
        /// </summary>
        public static string HumDesc {
            get {
                return ResourceManager.GetString("HumDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გადაუდებელი ჰუმანიტარული დახმარების შეტანის მიმართულება და პროპორციები.
        /// </summary>
        public static string HumDirection {
            get {
                return ResourceManager.GetString("HumDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ინფორმაცია გადაუდებელი ჰუმანიტარული დახმარების აუცილებლობის შესახებ.
        /// </summary>
        public static string HumInfo {
            get {
                return ResourceManager.GetString("HumInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ჰუმანიტარული დახმარების რაოდენობა.
        /// </summary>
        public static string HumQuantity {
            get {
                return ResourceManager.GetString("HumQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ჰუმანიტარული დახმარების აღწერა.
        /// </summary>
        public static string HumType {
            get {
                return ResourceManager.GetString("HumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მნიშვნელოვანი დოკუმენტები.
        /// </summary>
        public static string ImportantDocs {
            get {
                return ResourceManager.GetString("ImportantDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ინფორმაცია განსახორციელებელი პროექტის შესახებ.
        /// </summary>
        public static string InformationProjects {
            get {
                return ResourceManager.GetString("InformationProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სამოქალაქო ინტეგრაცია.
        /// </summary>
        public static string Integration {
            get {
                return ResourceManager.GetString("Integration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გამოგზავნილია თუ არა სამინისტროში პროექტი ოკუპირებულ ტერიტორიაზე საქმიანობის წარმართვის წესების მიხედვით?.
        /// </summary>
        public static string IsSentProject {
            get {
                return ResourceManager.GetString("IsSentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გვარი.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დასრულების თარიღი.
        /// </summary>
        public static string LDate {
            get {
                return ResourceManager.GetString("LDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ადგილობრივი პარტნიორი.
        /// </summary>
        public static string LocalPartner {
            get {
                return ResourceManager.GetString("LocalPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ინფორმაცია ადგილობრივი პარტნიორების შესახებ (დასახელება და საკონტაქტო ინფორმაცია).
        /// </summary>
        public static string LocalPartners {
            get {
                return ResourceManager.GetString("LocalPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შესვლა.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;შერიგებისა და სამოქალაქო თანასწორობის&lt;/b&gt;
        ///                            &lt;b&gt;საკითხებში საქართველოს სახელმწიფო&lt;/b&gt;
        ///                            &lt;b&gt;მინისტრის აპარატი&lt;/b&gt;.
        /// </summary>
        public static string LogoDesc {
            get {
                return ResourceManager.GetString("LogoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მთავარი.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ორგანიზაციის მისიის აღწერა.
        /// </summary>
        public static string MissionDesc {
            get {
                return ResourceManager.GetString("MissionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მოქალაქეობა.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სიახლეები.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to თვის ამბები.
        /// </summary>
        public static string NewsMonth {
            get {
                return ResourceManager.GetString("NewsMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სახელმწიფოთაშორისი ორგანიზაციებისა და საერთაშორისო განვითარების ორგანიზაციებისათვის, რომლებიც ახორციელებენ საქმიანობას ოკუპირებულ ტერიტორიებზე საქართველოს მთავრობასთან დადებული შეთანხმებების თანახმად.
        /// </summary>
        public static string NotifForm2Desc {
            get {
                return ResourceManager.GetString("NotifForm2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to საქართველოში მომუშავე და ოკუპირებული რეგიონების მონახულების მსურველმა პირებმა საჭიროა შეავსონ ქვემდებარე ფორმა. სანოტიფიკაციო ფორმა არ აკისრებს სახელმწიფო მინისტრის აპარატს რაიმე პასუხისმგებლობას და არ წარმოადგენს ოკუპირებული რეგიონების მონახულების ნებართვას. სანოტიფიკაციო ფორმა არის მხოლოდ ინფორმაციული ხასიათის. საერთაშორისო ჟურნალისტების მიერ მედიააკრედიტაციის მიღების მიზნით გთხოვთ დაუკავშირდეთ საქართველოს საგარეო საქმეთა სამინისტროს ან გადახვიდეთ ამ ბმულზე http://www.mfa.gov.ge.
        /// </summary>
        public static string NotificationDesc {
            get {
                return ResourceManager.GetString("NotificationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სანოტიფიკაციო ფორმა 1.
        /// </summary>
        public static string NotificationForm1 {
            get {
                return ResourceManager.GetString("NotificationForm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სანოტიფიკაციო ფორმა 2.
        /// </summary>
        public static string NotificationForm2 {
            get {
                return ResourceManager.GetString("NotificationForm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სანოტიფიკაციო ფორმა 2.
        /// </summary>
        public static string NotificationForm3 {
            get {
                return ResourceManager.GetString("NotificationForm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სანოტიფიკაციო ფორმები.
        /// </summary>
        public static string NotificationForms {
            get {
                return ResourceManager.GetString("NotificationForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ნოტიფიკაცია ოკუპირებულ ტერიტორიებზე შესვლის თაობაზე.
        /// </summary>
        public static string NotificationTitle {
            get {
                return ResourceManager.GetString("NotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მინისტრის აპარატი.
        /// </summary>
        public static string OfficeOfTheMinister {
            get {
                return ResourceManager.GetString("OfficeOfTheMinister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ორგანიზაციის სახელი.
        /// </summary>
        public static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სამხრეთ ოსეთი.
        /// </summary>
        public static string Ossetia {
            get {
                return ResourceManager.GetString("Ossetia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პასპორტის ნომერი.
        /// </summary>
        public static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პაროლი.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პერსონალური ინფორმაცია.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to საქართველოს ოკუპირებულ ტერიტორიებზე გადაუდებელი ჰუმანიტარული დახმარების წარმართვისათვის.
        /// </summary>
        public static string preface1 {
            get {
                return ResourceManager.GetString("preface1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to განსახორციელებელი პროექტი.
        /// </summary>
        public static string ProjectImplemented {
            get {
                return ResourceManager.GetString("ProjectImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პროექტის დასახელება.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პროექტის მიზანი.
        /// </summary>
        public static string Projectpurpose {
            get {
                return ResourceManager.GetString("Projectpurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დამატებითი ინფორმაცია.
        /// </summary>
        public static string Provideadditionalinformation {
            get {
                return ResourceManager.GetString("Provideadditionalinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შესვლის მიზანი.
        /// </summary>
        public static string PurposeofVisit {
            get {
                return ResourceManager.GetString("PurposeofVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დამიმახსოვრე.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ოკუპირებულ ტერიტორიებზე გამგზავრების მოსალოდნელი განრიგი .
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გაგზავნა.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სტატუს ნეიტრალური დოკუმენტები.
        /// </summary>
        public static string StatusNeutralDocs {
            get {
                return ResourceManager.GetString("StatusNeutralDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პროექტის სტატუსი (მიმდინარე, იდეა, დაფინანსებული, გაგრძელებული).
        /// </summary>
        public static string StatusOfProject {
            get {
                return ResourceManager.GetString("StatusOfProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ვიზიტორის სტატუსი პროექტში.
        /// </summary>
        public static string Statusofthevisitor {
            get {
                return ResourceManager.GetString("Statusofthevisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტელეფონი.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შენახვა.
        /// </summary>
        public static string TextSave {
            get {
                return ResourceManager.GetString("TextSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დროის შუალედი.
        /// </summary>
        public static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -მდე.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ატვირთეთ ფოტო.
        /// </summary>
        public static string UploadPhoto {
            get {
                return ResourceManager.GetString("UploadPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მომხმარებელი.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტრანსპორტის სახე.
        /// </summary>
        public static string Vehicletype {
            get {
                return ResourceManager.GetString("Vehicletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ვიზიტის ორგანიზატორი.
        /// </summary>
        public static string VisitOrganizedby {
            get {
                return ResourceManager.GetString("VisitOrganizedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ველი {0} სავალდებულოა.
        /// </summary>
        public static string WarningRequired {
            get {
                return ResourceManager.GetString("WarningRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ვებ-გვერდი.
        /// </summary>
        public static string WebPage {
            get {
                return ResourceManager.GetString("WebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მომხმარებელი ან პაროლი არასწორია.
        /// </summary>
        public static string WorningWrongPassword {
            get {
                return ResourceManager.GetString("WorningWrongPassword", resourceCulture);
            }
        }
    }
}
