#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SMR")]
	public partial class FilesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public FilesDataContext() : 
				base(global::Core.Properties.Settings.Default.SMRConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FilesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FilesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FilesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FilesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_List_Files", IsComposable=true)]
		public IQueryable<fn_List_FilesResult> fn_List_Files([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FileID", DbType="Int")] System.Nullable<int> fileID)
		{
			return this.CreateMethodCallQuery<fn_List_FilesResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fileID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_List_Gallery", IsComposable=true)]
		public IQueryable<fn_List_GalleryResult> fn_List_Gallery([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RecordID", DbType="Int")] System.Nullable<int> recordID)
		{
			return this.CreateMethodCallQuery<fn_List_GalleryResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), recordID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Files")]
		public int sp_Files([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FileID", DbType="Int")] ref System.Nullable<int> fileID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FileName", DbType="NVarChar(300)")] string fileName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DescriptionEN", DbType="NVarChar(MAX)")] string descriptionEN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DescriptionKA", DbType="NVarChar(MAX)")] string descriptionKA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DescriptionRU", DbType="NVarChar(MAX)")] string descriptionRU, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="URL", DbType="NVarChar(250)")] string uRL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TypeID", DbType="Int")] System.Nullable<int> typeID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, fileID, fileName, descriptionEN, descriptionKA, descriptionRU, uRL, typeID);
			fileID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Gallery")]
		public int sp_Gallery([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RecordID", DbType="Int")] ref System.Nullable<int> recordID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TitleEN", DbType="NVarChar(200)")] string titleEN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TitleKA", DbType="NVarChar(200)")] string titleKA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TitleRU", DbType="NVarChar(200)")] string titleRU, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DescriptionEN", DbType="NVarChar(MAX)")] string descriptionEN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DescriptionKA", DbType="NVarChar(MAX)")] string descriptionKA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DescriptionRU", DbType="NVarChar(MAX)")] string descriptionRU)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, recordID, titleEN, titleKA, titleRU, descriptionEN, descriptionKA, descriptionRU);
			recordID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class fn_List_FilesResult
	{
		
		private int _FileID;
		
		private string _FileName;
		
		private string _DescriptionEN;
		
		private string _DescriptionKA;
		
		private string _DescriptionRU;
		
		private string _URL;
		
		private System.Nullable<int> _TypeID;
		
		public fn_List_FilesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileID", DbType="Int NOT NULL")]
		public int FileID
		{
			get
			{
				return this._FileID;
			}
			set
			{
				if ((this._FileID != value))
				{
					this._FileID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescriptionEN", DbType="NVarChar(MAX)")]
		public string DescriptionEN
		{
			get
			{
				return this._DescriptionEN;
			}
			set
			{
				if ((this._DescriptionEN != value))
				{
					this._DescriptionEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescriptionKA", DbType="NVarChar(MAX)")]
		public string DescriptionKA
		{
			get
			{
				return this._DescriptionKA;
			}
			set
			{
				if ((this._DescriptionKA != value))
				{
					this._DescriptionKA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescriptionRU", DbType="NVarChar(MAX)")]
		public string DescriptionRU
		{
			get
			{
				return this._DescriptionRU;
			}
			set
			{
				if ((this._DescriptionRU != value))
				{
					this._DescriptionRU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this._URL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeID", DbType="Int")]
		public System.Nullable<int> TypeID
		{
			get
			{
				return this._TypeID;
			}
			set
			{
				if ((this._TypeID != value))
				{
					this._TypeID = value;
				}
			}
		}
	}
	
	public partial class fn_List_GalleryResult
	{
		
		private int _RecordID;
		
		private string _TitleEN;
		
		private string _TitleKA;
		
		private string _TitleRU;
		
		private string _DescriptionEN;
		
		private string _DescriptionKA;
		
		private string _DescriptionRU;
		
		public fn_List_GalleryResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", DbType="Int NOT NULL")]
		public int RecordID
		{
			get
			{
				return this._RecordID;
			}
			set
			{
				if ((this._RecordID != value))
				{
					this._RecordID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitleEN", DbType="NVarChar(200)")]
		public string TitleEN
		{
			get
			{
				return this._TitleEN;
			}
			set
			{
				if ((this._TitleEN != value))
				{
					this._TitleEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitleKA", DbType="NVarChar(200)")]
		public string TitleKA
		{
			get
			{
				return this._TitleKA;
			}
			set
			{
				if ((this._TitleKA != value))
				{
					this._TitleKA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitleRU", DbType="NVarChar(200)")]
		public string TitleRU
		{
			get
			{
				return this._TitleRU;
			}
			set
			{
				if ((this._TitleRU != value))
				{
					this._TitleRU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescriptionEN", DbType="NVarChar(MAX)")]
		public string DescriptionEN
		{
			get
			{
				return this._DescriptionEN;
			}
			set
			{
				if ((this._DescriptionEN != value))
				{
					this._DescriptionEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescriptionKA", DbType="NVarChar(MAX)")]
		public string DescriptionKA
		{
			get
			{
				return this._DescriptionKA;
			}
			set
			{
				if ((this._DescriptionKA != value))
				{
					this._DescriptionKA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescriptionRU", DbType="NVarChar(MAX)")]
		public string DescriptionRU
		{
			get
			{
				return this._DescriptionRU;
			}
			set
			{
				if ((this._DescriptionRU != value))
				{
					this._DescriptionRU = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
