<?xml version="1.0" encoding="utf-8"?><Database Name="SMR" Class="ToolsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=server.abs.ge,1443;Initial Catalog=SMR;Persist Security Info=True;User ID=sa" SettingsObjectName="Core.Properties.Settings" SettingsPropertyName="SMRConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_Dictionaries" Method="sp_Dictionaries">
    <Parameter Name="iud" Type="System.Int32" DbType="Int" />
    <Parameter Name="DictionaryID" Parameter="dictionaryID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="CaptionEN" Parameter="captionEN" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="CaptionKA" Parameter="captionKA" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="CaptionRU" Parameter="captionRU" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Caption1" Parameter="caption1" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="CodeVal" Parameter="codeVal" Type="System.Int32" DbType="Int" />
    <Parameter Name="ParentID" Parameter="parentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Level" Parameter="level" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="Hierarchy" Parameter="hierarchy" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="StringCode" Parameter="stringCode" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="DictionaryCode" Parameter="dictionaryCode" Type="System.Int32" DbType="Int" />
    <Parameter Name="DefVal" Parameter="defVal" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Visible" Parameter="visible" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="SortVal" Parameter="sortVal" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.fn_List_Dictionaries" Method="fn_List_Dictionaries" IsComposable="true">
    <Parameter Name="Level" Parameter="level" Type="System.Int32" DbType="Int" />
    <Parameter Name="DictionaryCode" Parameter="dictionaryCode" Type="System.Int32" DbType="Int" />
    <Parameter Name="ShowInvisibleItems" Parameter="showInvisibleItems" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="fn_List_DictionariesResult">
      <Column Name="RowNum" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DictionaryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CaptionEN" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CaptionKA" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CaptionRU" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Caption1" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CodeVal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StringCode" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DictionaryCode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DefVal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Visible" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SortVal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CRTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.fn_List_Notifications" Method="fn_List_Notifications" IsComposable="true">
    <Parameter Name="RecordID" Parameter="recordID" Type="System.Int32" DbType="Int" />
    <ElementType Name="fn_List_NotificationsResult">
      <Column Name="RecordID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="FName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PassportN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Nationality" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Sex" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EnteryNote" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EnteryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LeaveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Organisator" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TransportType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Destination" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="HostName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="HostContact" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EmFName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="EmLName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="EmAddress" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="EmMobile" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="VisitorStatus" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ProjectTitle" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="ProjectNote" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ProjectFDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProjectLDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Partner" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="IsSent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="WebPage" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RegFileURL" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MissionDesc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Contact" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Desc1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Desc2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Donors" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Term" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Proportions" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="OrgName" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="ProjectStatus" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Results" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsActualProjects" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ProjectResults" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FinanceInfo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PartnerInfo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DepartPlan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Notifications" Method="sp_Notifications">
    <Parameter Name="iud" Type="System.Int32" DbType="Int" />
    <Parameter Name="RecordID" Parameter="recordID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="NotificationTypeID" Parameter="notificationTypeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="URL" Parameter="uRL" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="Fname" Parameter="fname" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Lname" Parameter="lname" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Mobile" Parameter="mobile" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Fax" Parameter="fax" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="PassportN" Parameter="passportN" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Nationality" Parameter="nationality" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Bdate" Parameter="bdate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Sex" Parameter="sex" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="EnteryNote" Parameter="enteryNote" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="EnteryDate" Parameter="enteryDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="LeaveDate" Parameter="leaveDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Organisator" Parameter="organisator" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="TransportType" Parameter="transportType" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Destination" Parameter="destination" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="HostName" Parameter="hostName" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="HostContact" Parameter="hostContact" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="EmFName" Parameter="emFName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="EmLName" Parameter="emLName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="EmAddress" Parameter="emAddress" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="EmMobile" Parameter="emMobile" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="VisitorStatus" Parameter="visitorStatus" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="ProjectTitle" Parameter="projectTitle" Type="System.String" DbType="NVarChar(300)" />
    <Parameter Name="ProjectNote" Parameter="projectNote" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="ProjectFDate" Parameter="projectFDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ProjectLDate" Parameter="projectLDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Partner" Parameter="partner" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="IsSent" Parameter="isSent" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Note" Parameter="note" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="WebPage" Parameter="webPage" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="RegFileURL" Parameter="regFileURL" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="MissionDesc" Parameter="missionDesc" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Contact" Parameter="contact" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="Desc1" Parameter="desc1" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Desc2" Parameter="desc2" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Number" Parameter="number" Type="System.Int32" DbType="Int" />
    <Parameter Name="Donors" Parameter="donors" Type="System.String" DbType="NVarChar(300)" />
    <Parameter Name="Term" Parameter="term" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Proportions" Parameter="proportions" Type="System.String" DbType="NVarChar(300)" />
    <Parameter Name="OrgName" Parameter="orgName" Type="System.String" DbType="NVarChar(300)" />
    <Parameter Name="ProjectStatus" Parameter="projectStatus" Type="System.String" DbType="NVarChar(300)" />
    <Parameter Name="Results" Parameter="results" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="IsActualProjects" Parameter="isActualProjects" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ProjectResults" Parameter="projectResults" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="FinanceInfo" Parameter="financeInfo" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="PartnerInfo" Parameter="partnerInfo" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DepartPlan" Parameter="departPlan" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
</Database>