#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SMR")]
	public partial class ToolsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ToolsDataContext() : 
				base(global::Core.Properties.Settings.Default.SMRConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ToolsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ToolsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ToolsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ToolsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Dictionaries")]
		public int sp_Dictionaries([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DictionaryID", DbType="Int")] ref System.Nullable<int> dictionaryID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CaptionEN", DbType="NVarChar(200)")] string captionEN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CaptionKA", DbType="NVarChar(200)")] string captionKA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CaptionRU", DbType="NVarChar(200)")] string captionRU, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Caption1", DbType="NVarChar(200)")] string caption1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodeVal", DbType="Int")] System.Nullable<int> codeVal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentID", DbType="Int")] System.Nullable<int> parentID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Level", DbType="SmallInt")] System.Nullable<short> level, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Hierarchy", DbType="VarChar(200)")] string hierarchy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StringCode", DbType="NVarChar(100)")] string stringCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DictionaryCode", DbType="Int")] System.Nullable<int> dictionaryCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DefVal", DbType="Bit")] System.Nullable<bool> defVal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Visible", DbType="Bit")] System.Nullable<bool> visible, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortVal", DbType="Int")] System.Nullable<int> sortVal)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, dictionaryID, captionEN, captionKA, captionRU, caption1, codeVal, parentID, level, hierarchy, stringCode, dictionaryCode, defVal, visible, sortVal);
			dictionaryID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_List_Dictionaries", IsComposable=true)]
		public IQueryable<fn_List_DictionariesResult> fn_List_Dictionaries([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Level", DbType="Int")] System.Nullable<int> level, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DictionaryCode", DbType="Int")] System.Nullable<int> dictionaryCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShowInvisibleItems", DbType="Bit")] System.Nullable<bool> showInvisibleItems)
		{
			return this.CreateMethodCallQuery<fn_List_DictionariesResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), level, dictionaryCode, showInvisibleItems);
		}
	}
	
	public partial class fn_List_DictionariesResult
	{
		
		private System.Nullable<long> _RowNum;
		
		private int _DictionaryID;
		
		private string _CaptionEN;
		
		private string _CaptionKA;
		
		private string _CaptionRU;
		
		private string _Caption1;
		
		private System.Nullable<int> _CodeVal;
		
		private System.Nullable<int> _ParentID;
		
		private string _StringCode;
		
		private System.Nullable<short> _DictionaryCode;
		
		private System.Nullable<bool> _DefVal;
		
		private System.Nullable<bool> _Visible;
		
		private System.Nullable<int> _SortVal;
		
		private System.DateTime _CRTime;
		
		public fn_List_DictionariesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNum", DbType="BigInt")]
		public System.Nullable<long> RowNum
		{
			get
			{
				return this._RowNum;
			}
			set
			{
				if ((this._RowNum != value))
				{
					this._RowNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DictionaryID", DbType="Int NOT NULL")]
		public int DictionaryID
		{
			get
			{
				return this._DictionaryID;
			}
			set
			{
				if ((this._DictionaryID != value))
				{
					this._DictionaryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaptionEN", DbType="NVarChar(200)")]
		public string CaptionEN
		{
			get
			{
				return this._CaptionEN;
			}
			set
			{
				if ((this._CaptionEN != value))
				{
					this._CaptionEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaptionKA", DbType="NVarChar(200)")]
		public string CaptionKA
		{
			get
			{
				return this._CaptionKA;
			}
			set
			{
				if ((this._CaptionKA != value))
				{
					this._CaptionKA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaptionRU", DbType="NVarChar(200)")]
		public string CaptionRU
		{
			get
			{
				return this._CaptionRU;
			}
			set
			{
				if ((this._CaptionRU != value))
				{
					this._CaptionRU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption1", DbType="NVarChar(200)")]
		public string Caption1
		{
			get
			{
				return this._Caption1;
			}
			set
			{
				if ((this._Caption1 != value))
				{
					this._Caption1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeVal", DbType="Int")]
		public System.Nullable<int> CodeVal
		{
			get
			{
				return this._CodeVal;
			}
			set
			{
				if ((this._CodeVal != value))
				{
					this._CodeVal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int")]
		public System.Nullable<int> ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this._ParentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StringCode", DbType="NVarChar(100)")]
		public string StringCode
		{
			get
			{
				return this._StringCode;
			}
			set
			{
				if ((this._StringCode != value))
				{
					this._StringCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DictionaryCode", DbType="SmallInt")]
		public System.Nullable<short> DictionaryCode
		{
			get
			{
				return this._DictionaryCode;
			}
			set
			{
				if ((this._DictionaryCode != value))
				{
					this._DictionaryCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefVal", DbType="Bit")]
		public System.Nullable<bool> DefVal
		{
			get
			{
				return this._DefVal;
			}
			set
			{
				if ((this._DefVal != value))
				{
					this._DefVal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visible", DbType="Bit")]
		public System.Nullable<bool> Visible
		{
			get
			{
				return this._Visible;
			}
			set
			{
				if ((this._Visible != value))
				{
					this._Visible = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortVal", DbType="Int")]
		public System.Nullable<int> SortVal
		{
			get
			{
				return this._SortVal;
			}
			set
			{
				if ((this._SortVal != value))
				{
					this._SortVal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime NOT NULL")]
		public System.DateTime CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
